### PR TITLE
Add some feature to video player

### PR DESCRIPTION
**Pull request by hanghang**
Hello, I noticed forward button of exoplayer was removed in recent releases,
so I added simple gesture support to the player,  for fast forward/backward. hope you like it.

Change list:
1.  gesture support
2. add a rotate button for fast screen orientation toggle
3. `WindowInsetsController` does not work perfectly on some devices or customized ROMs, use deprecated `window.decorView.systemUiVisibility` on these devices instead.  this option is default to false in preferences.

### CODE REVIEW

**Comment by hardcore-sushi** [comment]
Thank you very much for your PR.
Gesture could be good but I don't think it's the best solution because they can be used unintentionally. Instead, I had planned to implement double-click controls (like on YouTube). Double-click on the right side to seek +5s and double-click on the left to rewind 5s.
Also, I don't want to change the current fullscreen behavior. Why not just rewrite `hideSystemUi` in `FileViewerActivity` to use `window.decorView.systemUiVisibility` if legacy mode is enable and otherwise just do what was previously there?
The toggle orientation button is a great idea but I don't know where to put it to have a neat interface.

**Comment by hanghang** [comment]
Double-click controls would be good idea too, I took the idea from an app called MX Player which supports both gesture and double click. They are both OK to me. 

> I don't want to change the current fullscreen behavior.

Then the code in "else" part of `override fun hideSystemUi()` is not necessary I guess.

**Comment by hardcore-sushi** [comment]
Yes VLC implements both as well but I don't like gestures so much. I prefer explicit controls, less likely to be used by mistake (yes I'm a bit oldschool).
I suggest to replace your "else" branch by what's already in `hideSystemUi`. Also, I think it would be better to not override `hideSystemUi` but modify it directly in `FileViewerActivity` so all file viewers get the compatibility fix.
For the rotate button, maybe we can place it on top right. I think it should be white, and the same size as ExoPlayer control buttons.
Would you like to reopen this PR for this 2 modifications?

**Comment by hanghang** [comment]
OK, I'll change the code and reopen for the last 2 modifications.

**Comment by hanghang** [comment]
I made the changes. but I'm still not sure if the rotate button is OK now, adjust position/style if you like.

**Comment by hardcore-sushi** [comment]
Thank you very much for your contribution ❤️
Last question: why did you use this icon for legacy mode?

**Comment by hanghang** [comment]
Because the codes in legacy mode have been marked as deprecated, sooner or later they will become unavailable and should be deleted.
I guess this kind of icon like `system` notifies people this is not a normal feature only for some third-party ROMs which have problem in using `WindowInsetsController`.

**Comment by hardcore-sushi** [comment]
You're right. I squashed & merged into master (be802aa5af51e16862f1f6cddc85c69f451ba927). However that's strange, your name doesn't appear in the "Contributors" section. Do you know why?

**Comment by hanghang** [comment]
I don't know why, but that's OK.

**Comment by hardcore-sushi** [comment]
I found a [thread](https://github.community/t/bug-new-contributors-section-does-sometimes-not-match-the-contributors-tab-under-insights) that explains the issue. Maybe your name will appear when the cache will be reloaded.

**Comment by hanghang** [comment]
Maybe they are running a async job to update cache, Thanks you.

**Pull request merged**
