### PR TITLE
ptbr update

### PR DESCRIPTION
**Pull request by mezysinc**
missing strings

### CODE REVIEW

**Comment by mezysinc** [comment]
by mistake uploaded wrong strings but it's good now

**Comment by hardcore-sushi** [comment]
No problem, can you please squash your commits ?

**Comment by mezysinc** [comment]
Well, I'm not able to squash it via UI, I tried deleting first commit but it didn't do much, merge it locally and apply commit the way you prefer

**Comment by hardcore-sushi** [comment]
OK, I squashed your commits and merged them into master. GitHub doesn't detect it so I'm closing this PR.

**Pull request closed without merging**
