### PR TITLE
Updated Russian language

### PR DESCRIPTION
**Pull request by solokot**

### CODE REVIEW

**Comment by hardcore-sushi** [comment]
Very reactive !
I'm waiting to finish the development of the next version before merging, just in case I add other strings.

**Comment by solokot** [comment]
Hello!
Okay, if there are plans to add other strings, I'll close this pull.
A small wish: after merging the sources of the new version, do a short pause before releasing (compiling), so that translators can be updated translation for upcoming version.

**Comment by solokot** [comment]
24 hours, in my opinion, is quite enough

**Comment by hardcore-sushi** [comment]
OK I think I will make a new release soon. You can re-open this pull-request if you want.

**Pull request closed without merging**
