### PR TITLE
Add a PDF viewer

### PR DESCRIPTION
**Pull request by hanghang**
Add a PDF viewer to view PDF documents.

### CODE REVIEW

**Comment by hardcore-sushi** [comment]
Wow I tested it, that's awesome.
Unfortunately the library you use would introduce a high risk of supply chain attack in DroidFS. I also found [this](https://github.com/barteksc/PdfiumAndroid/blob/103d5855f797af78a6f33f94cb306ef1c23b2290/build.gradle#L74) in a sub-library. We don't really want to execute arbitrary gradle script from GitHub in a security app project.
Another drawback is that it increases a lot the APK size (https://github.com/mhiew/AndroidPdfViewer#why-resulting-apk-is-so-big). My APK was ~10MB larger for just one ABI.
A solution would be to use a library from Google, as it already provides the majority of code in DroidFS, or to use a small library from trustworthy developers that does not depends on other libraries from random developers.

**Comment by hanghang** [comment]
So sorry for the risk, I'll try Google's library later.

**Comment by hardcore-sushi** [comment]
Do not apologize, this is a good idea, but DroidFS aims to be safe, so we have to be careful when using third-party code.
I don't know if Google has a PDF library, but if we find a small independent library I think it would be better.

**Comment by ralaud** [comment]
I am not a developer. But maybe this implementation could help I think [https://github.com/GrapheneOS/PdfViewer](https://github.com/GrapheneOS/PdfViewer)

**Comment by hardcore-sushi** [comment]
Yes that could help a lot, but that's not a library, so we would need to either fork the project or extract relevant code from it.

**Comment by ralaud** [comment]
I found this library https://mupdf.com/docs/android-library.html it is from the developer who released these apps https://search.f-droid.org/?q=Mupdf

**Comment by hardcore-sushi** [comment]
Interesting, but it seems we can only download the binaries from the maven's ghostscript repository. I don't know if we could trust this source. Otherwise we would need to build the lib from source.

**Comment by ralaud** [comment]
> I don't know if we could trust this source.

I don't know either. That is no evidence for trust, but I know that [Sumatrapdf](https://github.com/sumatrapdfreader/sumatrapdf) is also based on Mupdf library.

I understand that you are so careful due to your app is a security app. I appreciate this kind of thinking and your work.

> Otherwise we would need to build the lib from source.

And I would do it this way too, even if it result in more work.

**Comment by hardcore-sushi** [comment]
b18232615d93afdda13a30cef22468ea549b8e8d: Thanks to the GraphenOS' code, DroidFS can now open PDF files!

**Pull request closed without merging**
