### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by solokot**
Attempt #3 :)

### CODE REVIEW

**Comment by solokot** [comment]
Of course, I keep track of changes in automatic mode, just by third-party soft

**Comment by hardcore-sushi** [comment]
Can I ask you what is the software you use?

**Comment by solokot** [comment]
It's not a secret, with this thing: https://web.archive.org/web/20040612120939/http://www.activerefresh.com/

Yes, the program is old, it uses IE engine, but I haven't found anything better so far: Its main advantage is ability to parse sites by templates and generate news post with only necessary information (also by templates). And it does it on its own, not on some third-party server. They used to know how to write software: neither .net nor Qt ;)

**Comment by hardcore-sushi** [comment]
OK I see. But why don't you simply watch the repository? You would receive a notification every time something happens. Wouldn't it be easier?
I'm looking to improve communication between contributors, and maybe also users. Do you think a Mastodon account, or a Matrix or XMPP chat room would be a good way? Or do you have any better suggestions?

**Comment by solokot** [comment]
>simply watch the repository
This is easier, but e-mails come on every "sneeze" (commit), and so I follow only the change "values\*.xml".
>Mastodon account, or a Matrix or XMPP chat room would be a good way?
It's the first time I've heard about Mastodon. I've watched Matrix and XMPP, but I couldn't interest my social circle in them, so there's no real experience, but I can install it.

**Pull request merged**
